service: serverless-graphql-rest

provider:
  name: aws
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

functions:
  graphql:
    timeout: 100 # optional, in seconds, default is 6
    handler: handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get